#!/bin/sh
module="ssd"
device="ssd"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes
rm -f /dev/${device}0
rm -f /dev/${device}1
rm -f /dev/${device}2
rm -f /dev/${device}3
rm -f /dev/${device}4
rm -f /dev/${device}5
rm -f /dev/${device}6
